# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESTOQUE',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('barras', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=40)),
                ('und', models.CharField(max_length=40)),
                ('qtd', models.SmallIntegerField()),
                ('preco_venda', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tamanho', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'ESTOQUE',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_cliente', models.CharField(max_length=30, verbose_name='Nome do Cliente')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.IntegerField()),
                ('data_do_veiculo', models.DateField()),
                ('modelo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=7)),
                ('cpf_cnpj', models.IntegerField()),
                ('inscricao', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
    ]
