# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
