# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-05 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_orcamento_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='orcamento_id',
            new_name='orcamento',
        ),
    ]
