# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180504_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cpf_cnpj',
            field=models.IntegerField(verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_do_veiculo',
            field=models.DateField(verbose_name='Data do Veículo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='inscricao',
            field=models.CharField(max_length=30, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='modelo',
            field=models.CharField(max_length=30, verbose_name='Modelo do Veículo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='nome_do_cliente',
            field=models.CharField(max_length=100, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='placa',
            field=models.CharField(max_length=7, verbose_name='Placa de Veículo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
